site_name: 南宫春水的博客
site_url: https://Martinbits007.github.io

theme: material
nav:
  - 首页: index.md
  - 第一篇博客: START.md
  - python学习日记: python.md
  - 滚动新闻web开发日志: new_apps.md
  - fastapi开发框架：Fastapi.md